name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey, @${{ github.actor }}, welcome to Vyxal! Thanks for creating an issue, that's cool!🙌"
        pr-message: "Hi, @${{ github.actor }}! Thank you for helping us make Vyxal better, stay epic!😎"
